import { auth } from './firebase.js';
import { onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/10.8.0/firebase-auth.js';

onAuthStateChanged(auth, (user) => {
    if (!user) window.location.href = 'login.html';
});

(function configurarListaProdutos() {
    const normalizar = (valor) => String(valor ?? '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().trim();
    function instalarEstilos() {
        if (document.getElementById('lista-produtos-mobile-style')) return;
        const style=document.createElement('style'); style.id='lista-produtos-mobile-style'; style.textContent=`
@media(max-width:749px){html,body{width:100%!important;max-width:100%!important;overflow-x:hidden!important}.container,main,.admin-grid,.products-section,.products-section.card{width:100%!important;max-width:100%!important;min-width:0!important}.products-filters{display:grid!important;grid-template-columns:1fr!important;gap:8px!important}.products-filters input,.products-filters select{width:100%!important;min-width:0!important;box-sizing:border-box!important}.table-wrapper{width:100%!important;max-width:100%!important;overflow:visible!important}.table-wrapper table{width:100%!important;min-width:0!important;display:block!important}.table-wrapper thead{display:none!important}.table-wrapper tbody{display:block!important;width:100%!important}.table-wrapper tbody tr{display:block!important;width:100%!important;max-width:100%!important;min-width:0!important;box-sizing:border-box!important;margin:0 0 12px!important;padding:12px!important;border:1px solid var(--borda,#dfe5df)!important;border-radius:14px!important;background:#fff!important;overflow:hidden!important}.table-wrapper tbody tr[hidden]{display:none!important}.table-wrapper td{display:block!important;width:100%!important;max-width:100%!important;min-width:0!important;box-sizing:border-box!important;padding:5px 0!important;border:0!important;overflow-wrap:anywhere!important;word-break:break-word!important}.table-wrapper td:first-child{float:left!important;width:62px!important;max-width:62px!important;padding:0 10px 8px 0!important}.table-wrapper td:nth-child(2){min-height:52px!important;display:flex!important;align-items:center!important}.table-wrapper td:nth-child(6){clear:both!important;padding-top:10px!important}.table-wrapper .acoes-celula{display:grid!important;grid-template-columns:1fr 1fr!important;gap:8px!important;width:100%!important}.table-wrapper .btn-editar,.table-wrapper .btn-excluir{width:100%!important;min-width:0!important;min-height:42px!important}.table-wrapper .img-tabela{display:block!important;width:52px!important;height:52px!important;object-fit:cover!important}
#campo-imagem-arquivo{display:block!important;width:100%!important;margin-top:8px!important}#sf-galeria-btn{display:flex!important;width:100%!important;min-height:48px!important;align-items:center!important;justify-content:center!important;margin-bottom:8px!important;border:0!important;border-radius:10px!important;background:#2e7d32!important;color:#fff!important;font-weight:800!important;font-size:.8rem!important;cursor:pointer!important}#imagem-arquivo{display:block!important;width:100%!important;min-height:48px!important;padding:10px!important;border:1.5px dashed #2e7d32!important;border-radius:12px!important;background:#f7fbf7!important;font-size:.76rem!important}}
#campo-imagem-arquivo.sf-galeria-ativo{display:block!important;width:100%!important;margin-top:8px!important}#sf-galeria-btn{display:flex;align-items:center;justify-content:center;min-height:46px;width:100%;margin:0 0 8px;border:0;border-radius:10px;background:#2e7d32;color:#fff;font-weight:800;font-size:.78rem;cursor:pointer}#sf-galeria-btn:active{transform:scale(.99)}#sf-galeria-ajuda{display:block;margin:6px 0;color:#607d8b;font-size:.68rem;line-height:1.4}`; document.head.appendChild(style);
    }
    function configurarGaleria(){const campo=document.getElementById('campo-imagem-arquivo'),arquivo=document.getElementById('imagem-arquivo'),radios=document.getElementsByName('tipo-imagem');if(!campo||!arquivo)return;campo.classList.add('sf-galeria-ativo');campo.style.setProperty('display','block','important');if(radios.length){radios[0].value='arquivo';radios[0].checked=true}let botao=document.getElementById('sf-galeria-btn');if(!botao){botao=document.createElement('button');botao.id='sf-galeria-btn';botao.type='button';botao.textContent='📷 Escolher imagem da galeria';botao.addEventListener('click',()=>arquivo.click());campo.insertBefore(botao,arquivo)}if(!document.getElementById('sf-galeria-ajuda')){const ajuda=document.createElement('div');ajuda.id='sf-galeria-ajuda';ajuda.textContent='Escolha uma foto da galeria do celular. A imagem será enviada ao salvar.';campo.appendChild(ajuda)}arquivo.setAttribute('accept','image/*');arquivo.removeAttribute('capture');}
    function obter(){return{busca:document.getElementById('filtro-produto'),categoria:document.getElementById('filtro-categoria'),ordem:document.getElementById('filtro-ordem'),tbody:document.getElementById('lista-produtos-body')}}
    function aplicarFiltros(){const{busca,categoria,ordem,tbody}=obter();if(!tbody)return;const termo=normalizar(busca?.value),cat=normalizar(categoria?.value),linhas=[...tbody.querySelectorAll('tr')].filter(l=>l.querySelector('[data-id]'));linhas.forEach(l=>{const c=l.querySelectorAll('td'),nome=normalizar(c[1]?.textContent),catL=normalizar(c[2]?.textContent);l.hidden=!!(termo&&!nome.includes(termo))||!!(cat&&cat!=='todas'&&catL!==cat)});const modo=ordem?.value;if(modo==='az'||modo==='za'){linhas.sort((a,b)=>{const na=normalizar(a.querySelectorAll('td')[1]?.textContent),nb=normalizar(b.querySelectorAll('td')[1]?.textContent),r=na.localeCompare(nb,'pt-BR',{sensitivity:'base',numeric:true});return modo==='az'?r:-r});linhas.forEach(l=>tbody.appendChild(l))}}
    function ligarEventos(){if(document.documentElement.dataset.sfFiltrosLigados==='1')return;document.documentElement.dataset.sfFiltrosLigados='1';document.addEventListener('input',e=>{if(e.target?.id==='filtro-produto')aplicarFiltros()});document.addEventListener('change',e=>{if(['filtro-produto','filtro-categoria','filtro-ordem'].includes(e.target?.id))aplicarFiltros()});const observar=()=>{const tbody=document.getElementById('lista-produtos-body');if(!tbody||tbody.dataset.sfObserver==='1'){configurarGaleria();return}new MutationObserver(()=>{clearTimeout(window.__sfFiltroTimer);window.__sfFiltroTimer=setTimeout(()=>{configurarGaleria();aplicarFiltros()},30)}).observe(tbody,{childList:true});tbody.dataset.sfObserver='1';aplicarFiltros();configurarGaleria()};observar();const t=setInterval(observar,300);setTimeout(()=>clearInterval(t),15000)}
    function iniciar(){instalarEstilos();configurarGaleria();ligarEventos()} if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',iniciar,{once:true});else iniciar();
})();
