import { db } from './firebase.js';
import { collection, getDocs, addDoc, doc, getDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
import { calculateItem, deliveryFee, money } from './order-engine.js';
import { PEDIDOS_CONFIG } from './config.js';

let products=[];
const cart=new Map();
let observationTarget=null;
const $=id=>document.getElementById(id);

function fallbackImage(name){const n=String(name||'').toLowerCase();const map={'limão':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Lemon.jpg','mamão papaya':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Papaya.jpg','banana':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Banana_fruit.jpeg','abacaxi':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Pineapple.jpg','laranja pera':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Orange-Fruit-Pieces.jpg','caju':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Cashew.jpg','tâmara':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Dates.jpg','maçã':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Apple.jpg','manga palmer':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Mango.jpg','melancia':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Watermelon.jpg','melão':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Melon.jpg','pera macia':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Pear.jpg','morango':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Strawberry.jpg','uva preta':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Grapes.jpg','uva verde':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Grapes.jpg','abacate':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Avocado.jpg','goiaba':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Guava.jpg','água de coco':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Coconut.jpg','ovos caipira':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Chicken_eggs.jpg'};return map[n]||'';}
function measures(p){if(Array.isArray(p.measures)&&p.measures.length)return p.measures;const tiers=Array.isArray(p.priceTiers)?p.priceTiers:[];const base=[{quantity:1,unit:p.unit||'Un',price:Number(p.price||0)}];return base.concat(tiers.map(t=>({quantity:Number(t.minQty),unit:p.unit||'Un',price:Number(t.unitPrice)})));}
function measureLabel(m){const q=Number(m.quantity||m.lotSize||1);return m.unit==='Lote'?`Lote c/${q||1} UN`:m.unit||'Un';}
function priceLabel(m){return `${money(m.price)} por ${(m.unit||'Un').toLowerCase()}`;}
function selectedTotal(p,c){try{return calculateItem(p,c).total}catch{return 0}}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function render(){const q=$('search').value.toLowerCase().trim();const list=products.filter(p=>!q||String(p.name||'').toLowerCase().includes(q));$('products').innerHTML=list.length?list.map(p=>{const ms=measures(p);const c=cart.get(p.id)||{measureIndex:0,quantity:0};if(!ms[c.measureIndex])c.measureIndex=0;const m=ms[c.measureIndex];const src=p.image||fallbackImage(p.name);const fb=fallbackImage(p.name);return `<article class="product"><div class="product-top"><img class="photo" src="${escapeHtml(src)}" alt="${escapeHtml(p.name)}" onerror="this.onerror=null;this.src='${escapeHtml(fb)}'"><div><div class="name">${escapeHtml(p.name)}</div><div class="cat">${escapeHtml(p.category||'')}</div></div></div><div class="label">Escolha a unidade</div><div class="measure-buttons">${ms.map((x,i)=>`<button type="button" class="measure-btn ${i===c.measureIndex?'active':''}" onclick="chooseMeasure('${p.id}',${i})">${escapeHtml(measureLabel(x))}</button>`).join('')}</div><div class="price-row"><span class="price">${priceLabel(m)}</span>${m.unit==='Lote'?`<span class="hint">${Number(m.quantity||m.lotSize)||1} unidades no lote</span>`:''}</div><div class="controls"><span class="qty-label">Quantidade</span><div class="counter"><button onclick="changeQty('${p.id}',-1)">−</button><span>${c.quantity||0}</span><button onclick="changeQty('${p.id}',1)">+</button></div></div>${c.quantity?`<div class="selected-total">Total deste produto: <b>${money(selectedTotal(p,{...c,unit:m.unit,measureQuantity:m.quantity}))}</b></div><button class="obs-btn" onclick="openObservation('${p.id}')">${c.observation?'Editar observação':'Adicionar observação'}</button>`:''}</article>`}).join(''):'<div class="empty">Nenhum produto encontrado.</div>';updateCartButton();}
window.chooseMeasure=(id,index)=>{const c=cart.get(id)||{quantity:0};cart.set(id,{...c,measureIndex:index});render();};
window.changeQty=(id,delta)=>{const p=products.find(x=>x.id===id);if(!p)return;const c=cart.get(id)||{measureIndex:0,quantity:0};const quantity=Math.max(0,Number(c.quantity||0)+delta);if(quantity===0)cart.delete(id);else cart.set(id,{...c,quantity});render();};
window.openObservation=id=>{const p=products.find(x=>x.id===id);if(!p)return;observationTarget=id;$('obsProductName').textContent=`Para: ${p.name}`;$('obsInput').value=cart.get(id)?.observation||'';$('obsModal').classList.add('show');$('obsInput').focus();};
window.closeObservation=()=>{$('obsModal').classList.remove('show');observationTarget=null;};
window.saveObservation=()=>{if(!observationTarget)return;const c=cart.get(observationTarget);if(c)cart.set(observationTarget,{...c,observation:$('obsInput').value.trim()});window.closeObservation();render();};
function updateCartButton(){const count=[...cart.values()].reduce((s,c)=>s+Number(c.quantity||0),0);$('finish').textContent=count?`Finalizar pedido (${count})`:'Finalizar pedido';}
window.openReview=()=>{const items=[...cart.entries()].map(([id,c])=>{const p=products.find(x=>x.id===id),m=measures(p)[c.measureIndex||0];return {p,c,m};}).filter(x=>x.p&&x.c.quantity);if(!items.length){alert('Adicione pelo menos um produto à sacola.');return;}$('review').innerHTML=items.map(({p,c,m})=>`<div class="review-line"><div><div class="review-name">${escapeHtml(p.name)}</div><div class="review-sub">${c.quantity} × ${escapeHtml(measureLabel(m))} — ${money(selectedTotal(p,{...c,unit:m.unit,measureQuantity:m.quantity}))}</div>${c.observation?`<div class="obs-text">Obs.: ${escapeHtml(c.observation)}</div>`:''}</div><div class="review-controls"><button onclick="changeQty('${p.id}',-1)">−</button><span>${c.quantity}</span><button onclick="changeQty('${p.id}',1)">+</button><button class="remove-item" onclick="removeItem('${p.id}')">×</button></div></div>`).join('');refreshSummary();$('modal').classList.add('show');};
window.removeItem=id=>{cart.delete(id);render();if(cart.size)window.openReview();else window.closeReview();};
window.closeReview=()=>{$('modal').classList.remove('show');};
function refreshSummary(){let subtotal=0;for(const [id,c] of cart){const p=products.find(x=>x.id===id);if(!p)continue;const m=measures(p)[c.measureIndex||0];subtotal+=selectedTotal(p,{...c,unit:m.unit,measureQuantity:m.quantity});}const fee=deliveryFee(subtotal);$('reviewSummary').innerHTML=`<div class="review-summary-row"><span>Subtotal</span><strong>${money(subtotal)}</strong></div><div class="review-summary-row"><span>Taxa de entrega</span><strong class="${fee===0?'free':''}">${fee===0?'Grátis':money(fee)}</strong></div>`;$('reviewSummary').style.display='block';$('reviewTotal').textContent=money(subtotal+fee);}
function buildItems(){return [...cart.entries()].map(([id,c])=>{const p=products.find(x=>x.id===id),m=measures(p)[c.measureIndex||0];return calculateItem(p,{...c,unit:m.unit,measureQuantity:m.quantity});});}
function saoPauloCalendar(){const parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit',weekday:'short',hour:'2-digit',hour12:false}).formatToParts(new Date());return {year:Number(parts.find(p=>p.type==='year')?.value),month:Number(parts.find(p=>p.type==='month')?.value),day:Number(parts.find(p=>p.type==='day')?.value),weekday:parts.find(p=>p.type==='weekday')?.value,hour:Number(parts.find(p=>p.type==='hour')?.value||0)};}
function nextDelivery(){const now=saoPauloCalendar();let days=1;if(now.weekday==='Sat')days=2;else if(now.weekday==='Sun')days=1;else if(now.hour<13)days=0;const d=new Date(Date.UTC(now.year,now.month-1,now.day+days,12));while(d.getUTCDay()===0)d.setUTCDate(d.getUTCDate()+1);return d.toLocaleDateString('pt-BR',{timeZone:'UTC',weekday:'long',day:'2-digit',month:'2-digit'});}
async function responsibleNumber(){const snap=await getDoc(doc(db,PEDIDOS_CONFIG.collections.config,'bot'));if(!snap.exists())throw new Error('O número responsável pelos pedidos não está configurado.');let n=String(snap.data()?.responsibleNumber||'').replace(/\D/g,'');if(n.length===11)n='55'+n;if(n.length<12)throw new Error('O número responsável pelos pedidos não está configurado corretamente.');return n;}
function buildWhatsAppMessage(items){let text='🍍 *PEDIDO — SAMUEL FRUTAS*\n\n';items.forEach(i=>{text+=`• ${i.quantity} ${i.unit==='Lote'?`LT c/ ${Number(i.measureQuantity||1)} UN`:i.unit} — ${i.name} · ${money(i.total)}\n`;if(i.observation)text+=`  _OBS: ${i.observation}_\n`});const subtotal=items.reduce((s,i)=>s+Number(i.total),0),fee=deliveryFee(subtotal),total=subtotal+fee;text+=`\n💰 *Total: ${money(total)}*\n\n⚠️ _O Samuel irá confirmar o valor total._`;return text;}
window.sendOrder=async()=>{let items;try{items=buildItems();if(!items.length){alert('A sacola está vazia.');return;}const number=await responsibleNumber();const subtotal=items.reduce((s,i)=>s+Number(i.total),0),fee=deliveryFee(subtotal),total=subtotal+fee,scheduledFor=nextDelivery(),orderId=`ORD-${Date.now()}`;const order={orderId,items,subtotal,deliveryFee:fee,total,scheduledFor,observations:items.filter(i=>i.observation).map(i=>({name:i.name,observation:i.observation})),createdAt:serverTimestamp(),status:'aguardando_envio_whatsapp',source:'web'};$('sendButton').disabled=true;$('sendButton').textContent='Registrando pedido...';await addDoc(collection(db,PEDIDOS_CONFIG.collections.orders),order);const wa=`https://wa.me/${number}?text=${encodeURIComponent(buildWhatsAppMessage(items))}`;$('result').innerHTML=`<div class="result"><b>Pedido registrado!</b><p>Agora clique abaixo para enviar o pedido pelo WhatsApp.</p><a class="send" href="${wa}" target="_blank" rel="noopener">Abrir WhatsApp e enviar</a></div>`;cart.clear();render();}catch(e){console.error(e);alert(e?.message||'Não foi possível registrar o pedido. Verifique as regras do Firestore.');}finally{$('sendButton').disabled=false;$('sendButton').textContent='Enviar pedido pelo WhatsApp';}};
async function loadProducts(){try{const snap=await getDocs(collection(db,PEDIDOS_CONFIG.collections.products));products=snap.docs.map(d=>({id:d.id,...d.data()})).filter(p=>p.archived!==true);render();}catch(e){console.error(e);$('products').innerHTML='<div class="empty">Não foi possível carregar os produtos. O Firebase está conectado, mas as regras do Firestore precisam permitir a leitura da coleção products.</div>';}}
$('search').addEventListener('input',render);loadProducts();