import { db } from './firebase.js';
import { collection, getDocs, doc, getDoc, onSnapshot } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
import { calculateItem, deliveryFee, money } from './order-engine.js';
import { PEDIDOS_CONFIG } from './config.js';

let products=[];
const cart=new Map();
const $=id=>document.getElementById(id);
let siteOffline=false;
let stopSiteListener=null;

function fallbackImage(name){const n=String(name||'').toLowerCase();const map={'limão':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Lemon.jpg','mamão papaya':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Papaya.jpg','banana':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Banana_fruit.jpeg','abacaxi':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Pineapple.jpg','laranja pera':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Orange-Fruit-Pieces.jpg','caju':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Cashew.jpg','tâmara':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Dates.jpg','maçã':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Apple.jpg','manga palmer':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Mango.jpg','melancia':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Watermelon.jpg','melão':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Melon.jpg','pera macia':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Pear.jpg','morango':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Strawberry.jpg','uva preta':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Grapes.jpg','uva verde':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Grapes.jpg','abacate':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Avocado.jpg','goiaba':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Guava.jpg','água de coco':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Coconut.jpg','ovos caipira':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Chicken_eggs.jpg'};return map[n]||'';}
function measures(p){if(Array.isArray(p.measures)&&p.measures.length)return p.measures;const tiers=Array.isArray(p.priceTiers)?p.priceTiers:[];const base=[{quantity:1,unit:p.unit||'Un',price:Number(p.price||0)}];return base.concat(tiers.map(t=>({quantity:Number(t.minQty),unit:p.unit||'Un',price:Number(t.unitPrice)})));}
function measureLabel(m){const q=Number(m.quantity||m.lotSize||1);return m.unit==='Lote'?`Lote c/${q||1} UN`:m.unit||'Un';}
function priceLabel(m){return `${money(m.price)} por ${(m.unit||'Un').toLowerCase()}`;}
function selectedTotal(p,c){try{return calculateItem(p,c).total}catch{return 0}}
function escapeHtml(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));}
function showOffline(){document.body.innerHTML='<main style="min-height:100vh;display:flex;align-items:center;justify-content:center;padding:24px;background:#f4f6f5;font-family:Arial,sans-serif;color:#182230;text-align:center"><section style="max-width:520px;background:#fff;border:1px solid #e5e7eb;border-radius:20px;padding:32px;box-shadow:0 10px 30px rgba(16,24,40,.08)"><div style="font-size:48px;margin-bottom:14px">🔧</div><h1 style="margin:0 0 12px;font-size:28px">Site em manutenção</h1><p style="margin:0;color:#667085;font-size:17px;line-height:1.5">Estamos realizando alguns ajustes.<br><strong>Voltaremos em breve!</strong></p></section></main>';}
function render(){if(siteOffline){showOffline();return;}const q=$('search').value.toLowerCase().trim();const list=products.filter(p=>!q||String(p.name||'').toLowerCase().includes(q));$('products').innerHTML=list.length?list.map(p=>{const ms=measures(p);const c=cart.get(p.id)||{measureIndex:0,quantity:0};if(!ms[c.measureIndex])c.measureIndex=0;const m=ms[c.measureIndex];const src=p.image||fallbackImage(p.name);const fb=fallbackImage(p.name);return `<article class="product"><div class="product-top"><img class="photo" src="${escapeHtml(src)}" alt="${escapeHtml(p.name)}" onerror="this.onerror=null;this.src='${escapeHtml(fb)}'"><div><div class="name">${escapeHtml(p.name)}</div><div class="cat">${escapeHtml(p.category||'')}</div></div></div><div class="label">Escolha a unidade</div><div class="measure-buttons">${ms.map((x,i)=>`<button type="button" class="measure-btn ${i===c.measureIndex?'active':''}" onclick="chooseMeasure('${p.id}',${i})">${escapeHtml(measureLabel(x))}</button>`).join('')}</div><div class="price-row"><span class="price">${priceLabel(m)}</span>${m.unit==='Lote'?`<span class="hint">${Number(m.quantity||m.lotSize)||1} unidades no lote</span>`:''}</div><div class="controls"><span class="qty-label">Quantidade</span><div class="counter"><button type="button" onclick="changeQty('${p.id}',-1)">−</button><span id="qty-${p.id}">${c.quantity||0}</span><button type="button" onclick="changeQty('${p.id}',1)">+</button></div></div>${c.quantity?`<div class="selected-total" id="total-${p.id}">Total deste produto: <b>${money(selectedTotal(p,{...c,unit:m.unit,measureQuantity:m.quantity}))}</b></div><button type="button" class="product-obs-btn" onclick="openCartObservation('${p.id}')">${c.observation?'Editar observação':'Adicionar observação'}</button>`:''}</article>`}).join(''):'<div class="empty">Nenhum produto encontrado.</div>';updateCartButton();}
function updateCartButton(){const count=[...cart.values()].reduce((s,c)=>s+Number(c.quantity||0),0);$('finish').textContent=count?`Finalizar pedido (${count})`:'Finalizar pedido';}
function updateQtyUI(id){const p=products.find(x=>x.id===id);const c=cart.get(id);if(!p||!c)return;const qty=$(`qty-${id}`);if(qty)qty.textContent=String(c.quantity||0);const ms=measures(p),m=ms[Number(c.measureIndex)||0];const total=$(`total-${id}`);if(total&&m)total.innerHTML=`Total deste produto: <b>${money(selectedTotal(p,{...c,unit:m.unit,measureQuantity:m.quantity}))}</b>`;const obs=document.querySelector(`.product-obs-btn[onclick="openCartObservation('${id}')"]`);if(obs)obs.textContent=c.observation?'Editar observação':'Adicionar observação';}
window.chooseMeasure=(id,index)=>{const c=cart.get(id)||{quantity:0,observation:''};cart.set(id,{...c,measureIndex:Number(index)||0});render();};
window.changeQty=(id,delta)=>{const p=products.find(x=>x.id===id);if(!p)return;const c=cart.get(id)||{measureIndex:0,quantity:0,observation:''};const quantity=Math.max(0,Number(c.quantity||0)+Number(delta||0));if(quantity===0){cart.delete(id);const card=document.querySelector(`.product .counter button[onclick="changeQty('${id}',-1)"]`)?.closest('.product');if(card)card.remove();}else{cart.set(id,{...c,quantity});if(!document.getElementById(`qty-${id}`)){render();}else{updateQtyUI(id);}}updateCartButton();if($('modal')?.classList.contains('show'))renderCart();};
window.openReview=()=>{renderCart();$('modal').classList.add('show');};
window.closeReview=()=>{$('modal').classList.remove('show');};
function renderCart(){const items=[...cart.entries()].map(([id,c])=>{const p=products.find(x=>x.id===id);if(!p||Number(c.quantity)<=0)return null;const ms=measures(p);const m=ms[Number(c.measureIndex)||0];if(!m)return null;return {p,c,m,total:selectedTotal(p,{...c,unit:m.unit,measureQuantity:m.quantity})};}).filter(Boolean);if(!items.length){$('review').innerHTML='<div class="empty">A sacola está vazia.</div>';refreshSummary();return;}$('review').innerHTML=items.map(({p,c,m,total})=>`<div class="review-line" data-review-id="${escapeHtml(p.id)}"><div class="review-info"><div class="review-name">${escapeHtml(p.name)}</div><div class="review-sub">${c.quantity} × ${escapeHtml(measureLabel(m))} — ${money(total)}</div><div class="cart-measure"><div class="cart-measure-title">Alterar medida</div><div class="cart-measure-options">${measures(p).map((x,i)=>`<button type="button" class="cart-measure-btn ${i===Number(c.measureIndex||0)?'active':''}" onclick="changeReviewMeasure('${p.id}',${i})"><strong>${escapeHtml(measureLabel(x))}</strong><span>${escapeHtml(priceLabel(x))}</span></button>`).join('')}</div></div><div class="cart-observation">${c.observation?`<div class="obs-text">Obs.: ${escapeHtml(c.observation)}</div><button type="button" class="obs-btn" onclick="openCartObservation('${p.id}')">Editar observação</button>`:`<button type="button" class="obs-btn" onclick="openCartObservation('${p.id}')">Adicionar observação</button>`}</div></div><div class="review-controls"><button type="button" onclick="reviewQty('${p.id}',-1)">−</button><span>${c.quantity}</span><button type="button" onclick="reviewQty('${p.id}',1)">+</button><button type="button" class="remove-item" onclick="reviewRemove('${p.id}')">×</button></div></div>`).join('');refreshSummary();}
window.reviewQty=(id,delta)=>{const p=products.find(x=>x.id===id);if(!p)return;const c=cart.get(id);if(!c)return;const quantity=Math.max(0,Number(c.quantity||0)+Number(delta||0));if(quantity===0){cart.delete(id);renderCart();updateCartButton();if(!cart.size)closeReview();return;}cart.set(id,{...c,quantity});const line=document.querySelector(`.review-line[data-review-id="${id}"]`);if(line){const sub=line.querySelector('.review-sub');const m=measures(p)[Number(c.measureIndex)||0];if(sub&&m)sub.textContent=`${quantity} × ${measureLabel(m)} — ${money(selectedTotal(p,{...c,quantity,unit:m.unit,measureQuantity:m.quantity}))}`;const span=line.querySelector('.review-controls span');if(span)span.textContent=String(quantity);}else{renderCart();return;}refreshSummary();};
window.reviewRemove=id=>{cart.delete(id);render();renderCart();if(!cart.size)closeReview();};
window.changeReviewMeasure=(id,index)=>{const c=cart.get(id);if(!c)return;cart.set(id,{...c,measureIndex:Number(index)||0});renderCart();};
window.removeItem=id=>window.reviewRemove(id);
window.openCartObservation=id=>{const p=products.find(x=>x.id===id),c=cart.get(id);if(!p||!c)return;$('obsProductName').textContent=`Para: ${p.name}`;$('obsInput').value=c.observation||'';$('obsModal').dataset.productId=id;$('obsModal').classList.add('show');$('obsInput').focus();};
window.closeObservation=()=>{$('obsModal').classList.remove('show');delete $('obsModal').dataset.productId;};
window.saveObservation=()=>{const id=$('obsModal').dataset.productId;const c=cart.get(id);if(!c)return;cart.set(id,{...c,observation:$('obsInput').value.trim()});closeObservation();updateQtyUI(id);if($('modal')?.classList.contains('show'))renderCart();};
function refreshSummary(){let subtotal=0;for(const [id,c] of cart){const p=products.find(x=>x.id===id);if(!p||Number(c.quantity)<=0)continue;const m=measures(p)[Number(c.measureIndex)||0];if(!m)continue;subtotal+=selectedTotal(p,{...c,unit:m.unit,measureQuantity:m.quantity});}const fee=deliveryFee(subtotal);$('reviewSummary').innerHTML=`<div class="review-summary-row"><span>Subtotal</span><strong>${money(subtotal)}</strong></div><div class="review-summary-row"><span>Taxa de entrega</span><strong class="${fee===0?'free':''}">${fee===0?'Grátis':money(fee)}</strong></div>`;$('reviewSummary').style.display='block';$('reviewTotal').textContent=money(subtotal+fee);}
function buildItems(){const out=[];for(const [id,c] of cart.entries()){if(!c||Number(c.quantity)<=0)continue;const p=products.find(x=>x.id===id);if(!p)continue;const ms=measures(p);const m=ms[Number(c.measureIndex)||0];if(!m)continue;try{out.push(calculateItem(p,{...c,unit:m.unit,measureQuantity:m.quantity}));}catch(e){console.warn('Produto ignorado no envio:',p.name,e);}}return out;}
function saoPauloCalendar(){const parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit',weekday:'short',hour:'2-digit',hour12:false}).formatToParts(new Date());return {year:Number(parts.find(p=>p.type==='year')?.value),month:Number(parts.find(p=>p.type==='month')?.value),day:Number(parts.find(p=>p.type==='day')?.value),weekday:parts.find(p=>p.type==='weekday')?.value,hour:Number(parts.find(p=>p.type==='hour')?.value||0)};}
function nextDelivery(){const now=saoPauloCalendar();let days=1;if(now.weekday==='Sat')days=2;else if(now.weekday==='Sun')days=1;else if(now.hour<13)days=0;const d=new Date(Date.UTC(now.year,now.month-1,now.day+days,12));while(d.getUTCDay()===0)d.setUTCDate(d.getUTCDate()+1);return d.toLocaleDateString('pt-BR',{timeZone:'UTC',weekday:'long',day:'2-digit',month:'2-digit'});}
async function responsibleNumber(){const snap=await getDoc(doc(db,PEDIDOS_CONFIG.collections.config,'bot'));if(!snap.exists())throw new Error('O número responsável pelos pedidos não está configurado.');let n=String(snap.data()?.responsibleNumber||'').replace(/\D/g,'');if(n.length===11)n='55'+n;if(n.length<12)throw new Error('O número responsável pelos pedidos não está configurado corretamente.');return n;}
function buildWhatsAppMessage(items){let text='🍍 *PEDIDO — SAMUEL FRUTAS*\n\n';items.forEach(i=>{text+=`• ${i.quantity} ${i.unit==='Lote'?`LT c/ ${Number(i.measureQuantity||1)} UN`:i.unit} — ${i.name} · ${money(i.total)}\n`;if(i.observation)text+=`  _OBS: ${i.observation}_\n`});const subtotal=items.reduce((s,i)=>s+Number(i.total),0),fee=deliveryFee(subtotal),total=subtotal+fee;text+=`\n💰 *Total: ${money(total)}*\n\n⚠️ _O Samuel irá confirmar o valor total._`;return text;}
window.sendOrder=async()=>{try{if(siteOffline){alert('Site em manutenção. Voltaremos em breve!');return;}const items=buildItems();if(!items.length){alert('A sacola está vazia.');return;}const number=await responsibleNumber();window.location.href=`https://wa.me/${number}?text=${encodeURIComponent(buildWhatsAppMessage(items))}`;}catch(e){console.error(e);alert(e?.message||'Não foi possível abrir o WhatsApp.');}};
async function loadProducts(){try{const snap=await getDocs(collection(db,PEDIDOS_CONFIG.collections.products));products=snap.docs.map(d=>({id:d.id,...d.data()})).filter(p=>p.archived!==true);render();}catch(e){console.error(e);if(!siteOffline)$('products').innerHTML='<div class="empty">Não foi possível carregar os produtos. O Firebase está conectado, mas as regras do Firestore precisam permitir a leitura da coleção products.</div>';}}
function listenSiteStatus(){if(stopSiteListener)stopSiteListener();stopSiteListener=onSnapshot(doc(db,PEDIDOS_CONFIG.collections.config,'bot'),snap=>{siteOffline=Boolean(snap.data()?.siteOffline);render();},()=>{siteOffline=false;render();});}
listenSiteStatus();loadProducts();