import { db } from './firebase.js';
import { collection, getDocs, addDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
import { calculateItem, deliveryFee, money } from './order-engine.js';
import { PEDIDOS_CONFIG } from './config.js';

let products=[];
const cart=new Map();
let observationTarget=null;
const $=id=>document.getElementById(id);

function fallbackImage(name){const n=String(name||'').toLowerCase();const map={'limão':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Lemon.jpg','mamão papaya':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Papaya.jpg','banana':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Banana_fruit.jpeg','abacaxi':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Pineapple.jpg','laranja pera':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Orange-Fruit-Pieces.jpg','caju':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Cashew.jpg','tâmara':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Dates.jpg','maçã':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Apple.jpg','manga palmer':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Mango.jpg','melancia':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Watermelon.jpg','melão':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Melon.jpg','pera macia':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Pear.jpg','morango':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Strawberry.jpg','uva preta':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Grapes.jpg','uva verde':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Grapes.jpg','abacate':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Avocado.jpg','goiaba':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Guava.jpg','água de coco':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Coconut.jpg','ovos caipira':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Chicken_eggs.jpg'};return map[n]||'';}
function measures(p){if(Array.isArray(p.measures)&&p.measures.length)return p.measures;return [{quantity:1,unit:p.unit||'Un',price:Number(p.price||0)}];}
function measureLabel(m){const q=Number(m.quantity||m.lotSize||1);return m.unit==='Lote'?`Lote c/${q||1} UN`:m.unit||'Un';}
function priceLabel(m){return `${money(m.price)} por ${(m.unit||'Un').toLowerCase()}`;}
function selectedTotal(p,c){try{return calculateItem(p,c).total}catch{return 0;}}
function render(){const q=$('search').value.toLowerCase().trim();const list=products.filter(p=>!q||String(p.name||'').toLowerCase().includes(q));$('products').innerHTML=list.length?list.map(p=>{const ms=measures(p);const c=cart.get(p.id)||{measureIndex:0,quantity:0};if(!ms[c.measureIndex])c.measureIndex=0;const m=ms[c.measureIndex];const src=p.image||fallbackImage(p.name);return `<article class="product"><div class="product-top"><img class="photo" src="${src}" alt="${escapeHtml(p.name)}" onerror="this.style.display='none'"><div><div class="name">${escapeHtml(p.name)}</div><div class="cat">${escapeHtml(p.category||'')}</div></div></div><div class="label">Escolha a unidade</div><div class="measure-buttons">${ms.map((x,i)=>`<button class="measure-btn ${i===c.measureIndex?'active':''}" onclick="chooseMeasure('${p.id}',${i})">${escapeHtml(measureLabel(x))}</button>`).join('')}</div><div class="price-row"><span class="price">${priceLabel(m)}</span>${m.unit==='Lote'?`<span class="hint">${Number(m.quantity||m.lotSize)||1} unidades no lote</span>`:''}</div><div class="controls"><span class="qty-label">Quantidade</span><div class="counter"><button onclick="changeQty('${p.id}',-1)">−</button><span>${c.quantity||0}</span><button onclick="changeQty('${p.id}',1)">+</button></div></div>${c.quantity?`<div class="selected-total">Total deste produto: <b>${money(selectedTotal(p,{...c,unit:m.unit,measureQuantity:m.quantity}))}</b></div><button class="obs-btn" onclick="openObservation('${p.id}')">${c.observation?'Editar observação':'Adicionar observação'}</button>`:''}</article>`}).join(''):'<div class="empty">Nenhum produto encontrado.</div>';updateCartButton();}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
window.chooseMeasure=(id,index)=>{const c=cart.get(id)||{quantity:0};cart.set(id,{...c,measureIndex:index});render();};
window.changeQty=(id,delta)=>{const p=products.find(x=>x.id===id);if(!p)return;const c=cart.get(id)||{measureIndex:0,quantity:0};const quantity=Math.max(0,Number(c.quantity||0)+delta);if(quantity===0)cart.delete(id);else cart.set(id,{...c,quantity});render();};
window.openObservation=id=>{const p=products.find(x=>x.id===id);if(!p)return;observationTarget=id;$('obsProductName').textContent=`Para: ${p.name}`;$('obsInput').value=cart.get(id)?.observation||'';$('obsModal').classList.add('show');$('obsInput').focus();};
window.closeObservation=()=>{$('obsModal').classList.remove('show');observationTarget=null;};
window.saveObservation=()=>{if(!observationTarget)return;const c=cart.get(observationTarget);if(c)cart.set(observationTarget,{...c,observation:$('obsInput').value.trim()});window.closeObservation();render();};
function updateCartButton(){const count=[...cart.values()].reduce((s,c)=>s+Number(c.quantity||0),0);$('finish').textContent=count?`Finalizar pedido (${count})`:'Finalizar pedido';}
window.openReview=()=>{const items=[...cart.entries()].map(([id,c])=>{const p=products.find(x=>x.id===id),m=measures(p)[c.measureIndex||0];return {p,c,m};}).filter(x=>x.p&&x.c.quantity);if(!items.length){alert('Adicione pelo menos um produto à sacola.');return;}$('review').innerHTML=items.map(({p,c,m})=>`<div class="review-line"><div><div class="review-name">${escapeHtml(p.name)}</div><div class="review-sub">${c.quantity} × ${escapeHtml(measureLabel(m))} — ${money(selectedTotal(p,{...c,unit:m.unit,measureQuantity:m.quantity}))}</div>${c.observation?`<div class="obs-text">Obs.: ${escapeHtml(c.observation)}</div>`:''}</div><div class="review-controls"><button onclick="changeQty('${p.id}',-1)">−</button><span>${c.quantity}</span><button onclick="changeQty('${p.id}',1)">+</button><button class="remove-item" onclick="removeItem('${p.id}')">×</button></div></div>`).join('');refreshSummary();$('modal').classList.add('show');};
window.removeItem=id=>{cart.delete(id);render();if(cart.size)window.openReview();else window.closeReview();};
window.closeReview=()=>{$('modal').classList.remove('show');};
function refreshSummary(){let subtotal=0;for(const [id,c] of cart){const p=products.find(x=>x.id===id);if(!p)continue;const m=measures(p)[c.measureIndex||0];subtotal+=selectedTotal(p,{...c,unit:m.unit,measureQuantity:m.quantity});}const fee=deliveryFee(subtotal);$('reviewSummary').innerHTML=`<div class="review-summary-row"><span>Subtotal</span><strong>${money(subtotal)}</strong></div><div class="review-summary-row"><span>Taxa de entrega</span><strong class="${fee===0?'free':''}">${fee===0?'Grátis':money(fee)}</strong></div>`;$('reviewSummary').style.display='block';$('reviewTotal').textContent=money(subtotal+fee);}
function buildItems(){return [...cart.entries()].map(([id,c])=>{const p=products.find(x=>x.id===id),m=measures(p)[c.measureIndex||0];return calculateItem(p,{...c,unit:m.unit,measureQuantity:m.quantity});});}
function nextDelivery(){const d=new Date();const weekday=d.getDay(),hour=d.getHours();let days=1;if(weekday===6)days=2;else if(weekday===0)days=1;else if(hour<13)days=0;const base=new Date(d);base.setDate(base.getDate()+days);while(base.getDay()===0)base.setDate(base.getDate()+1);return base.toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'2-digit'});}
window.sendOrder=async()=>{const phone=String($('phone').value||'').replace(/\D/g,'');if(phone.length<10){alert('Informe seu WhatsApp com DDD.');return;}let items;try{items=buildItems();}catch(e){alert(e.message||'Não foi possível calcular o pedido.');return;}if(!items.length)return;const subtotal=items.reduce((s,i)=>s+Number(i.total),0),fee=deliveryFee(subtotal),total=subtotal+fee;const scheduledFor=nextDelivery();const orderId=`ORD-${Date.now()}`;const order={orderId,items,subtotal,deliveryFee:fee,total,scheduledFor,observations:items.filter(i=>i.observation).map(i=>({name:i.name,observation:i.observation})),createdAt:serverTimestamp(),status:'aguardando_envio_whatsapp',source:'web',phone};try{$('sendButton').disabled=true;$('sendButton').textContent='Enviando...';await addDoc(collection(db,PEDIDOS_CONFIG.collections.orders),order);const lines=['🛒 Pedido Samuel Frutas',...items.map(i=>`- ${i.quantity} x ${i.measureQuantity>1?`${i.measureQuantity} ${i.unit}`:i.unit} — ${i.name} — ${money(i.total)}`),'',`Subtotal: ${money(subtotal)}`,`Taxa de entrega: ${fee?money(fee):'Grátis'}`,`TOTAL: ${money(total)}`,`📅 Entrega: ${scheduledFor}`];if(order.observations.length)lines.push('','Observações:',...order.observations.map(o=>`- ${o.name}: ${o.observation}`));const wa=`https://wa.me/55${phone}?text=${encodeURIComponent(lines.join('\n'))}`;$('result').innerHTML=`<div class="result"><b>Pedido registrado!</b><p>Agora clique abaixo para enviar o pedido pelo WhatsApp.</p><a class="send" href="${wa}" target="_blank" rel="noopener">Abrir WhatsApp e enviar</a></div>`;cart.clear();}catch(e){console.error(e);alert('Não foi possível registrar o pedido. Verifique as regras de acesso do Firestore.');}finally{$('sendButton').disabled=false;$('sendButton').textContent='Enviar pedido pelo WhatsApp';}};
async function loadProducts(){try{const snap=await getDocs(collection(db,PEDIDOS_CONFIG.collections.products));products=snap.docs.map(d=>({id:d.id,...d.data()})).filter(p=>p.archived!==true);render();}catch(e){console.error(e);$('products').innerHTML='<div class="empty">Não foi possível carregar os produtos. O Firebase está conectado, mas as regras do Firestore precisam permitir a leitura da coleção products.</div>';}}
$('search').addEventListener('input',render);loadProducts();
