function norm(s){return String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();}
function unitNorm(u){const s=norm(u);if(['un','unidade','unidades'].includes(s))return'un';if(['dz','duzia','duzias'].includes(s))return'dz';if(['bdj','bdg','bandeja','bandejas'].includes(s))return'bdg';if(['cx','caixa','caixas'].includes(s))return'cx';if(['kg','quilo','quilos'].includes(s))return'kg';if(['lote','lotes'].includes(s))return'lote';if(['gf','garrafa','garrafas'].includes(s))return'gf';return s;}
function measuresFor(product){if(Array.isArray(product.measures)&&product.measures.length)return product.measures;const tiers=Array.isArray(product.priceTiers)?product.priceTiers:[];return [{quantity:1,unit:product.unit||'Un',price:Number(product.price||0)},...tiers.map(t=>({quantity:Number(t.minQty),unit:product.unit||'Un',price:Number(t.unitPrice)}))];}
function factorOf(m){const q=Number(m?.quantity||m?.lotSize||1)||1;const u=norm(m?.unit);if(['dz','duzia','duzias'].includes(u))return 12*q;if(['dezena','dezenas'].includes(u))return 10*q;if(['inteiro','inteira'].includes(u))return q;const f=String(m?.unit||'').match(/^(\d+(?:[.,]\d+)?)\s*\/\s*(\d+(?:[.,]\d+)?)$/);if(f){const a=Number(f[1].replace(',','.')),b=Number(f[2].replace(',','.'));if(a>0&&b>0)return q*a/b;}return q;}
function ceilStep(v,step){return Math.ceil((Number(v)-1e-9)/step)*step;}
function progressiveRound(v,m){return norm(m?.unit)==='lote'?ceilStep(v,.5):ceilStep(v,.1);}
function findMeasure(product,unit,measureQuantity){const ms=measuresFor(product).filter(m=>Number.isFinite(Number(m?.price))&&Number(m.price)>=0);const wanted=unit?unitNorm(unit):'';if(wanted){const exact=ms.find(m=>unitNorm(m.unit)===wanted&&Number(m.quantity)===Number(measureQuantity||1));if(exact)return exact;const one=ms.find(m=>unitNorm(m.unit)===wanted&&Number(m.quantity)===1);if(one)return one;}if(measureQuantity!=null){const q=ms.find(m=>Number(m.quantity)===Number(measureQuantity));if(q)return q;}const def=unitNorm(product.unit||'');if(def){const p=ms.find(m=>unitNorm(m.unit)===def&&Number(m.quantity||m.lotSize||1)===1);if(p)return p;const any=ms.find(m=>unitNorm(m.unit)===def);if(any)return any;}return ms.find(m=>Number(m.quantity||m.lotSize||1)===1)||ms[0]||null;}
function calculateSelection(product,quantity,measure){const ms=measuresFor(product).filter(m=>Number(m?.price||0)>0);if(!ms.length)return 0;const target=factorOf(measure)*quantity;const exact=ms.filter(m=>Math.abs(factorOf(m)-target)<1e-9).sort((a,b)=>factorOf(b)-factorOf(a))[0];if(exact)return Number(exact.price);const lower=ms.filter(m=>factorOf(m)<=target+1e-9).sort((a,b)=>factorOf(b)-factorOf(a))[0];if(lower){const base=factorOf(lower);return progressiveRound(target*(Number(lower.price)/base),lower);}return Number(measure.price)*quantity;}
export function calculateItem(product,cartItem){const quantity=Number(cartItem.quantity);const measure=findMeasure(product,cartItem.unit,cartItem.measureQuantity);if(!measure||!Number.isFinite(quantity)||quantity<=0)throw new Error(`Medida ou quantidade inválida para ${product.name}.`);return {productId:product.id,name:product.name,category:product.category||'',unit:measure.unit,measureQuantity:Number(measure.lotSize||measure.quantity)||1,quantity,unitPrice:calculateSelection(product,quantity,measure)/quantity,total:calculateSelection(product,quantity,measure),observation:String(cartItem.observation||'').trim()};}
export function deliveryFee(subtotal){if(subtotal>=50)return 0;if(subtotal>=20)return 3;return 5;}
export function money(n){return Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});}
