import { db } from "../firebase.js";
import { collection,getDocs } from "https://www.gstatic.com/firebasejs/10.8.0/firebase-firestore.js";
const WA="5521972837869";let P={frutas:[],legumes:[],verduras:[],aguaOvos:[]},C={},U={},catNow=null,type="Entrega",editKey=null;
const $=id=>document.getElementById(id),N=x=>String(x??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim(),num=x=>Number(String(x??"").replace(",","."))||0,fmt=x=>Number.isInteger(x)?String(x):String(x).replace(".",",");
const META={frutas:["Frutas","🍎"],legumes:["Legumes","🥕"],verduras:["Verduras","🥬"],aguaOvos:["Água de coco e ovos","🥥"]};const esc=x=>String(x??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll("\"","&quot;");
function category(v){let x=N(v);if(x.includes("legume"))return"legumes";if(x.includes("verdura"))return"verduras";if(x.includes("agua")||x.includes("ovo")||x.includes("coco"))return"aguaOvos";return"frutas"}
function getUnits(d){let r=d.unidades??d.units??d.unidade??d.unit??d.medidas??d.medida,a=[];if(Array.isArray(r))a=r;else if(typeof r==="string")a=r.split(/[,;|\n]+/);else if(r&&typeof r==="object")a=Object.keys(r).filter(k=>r[k]);a=a.map(x=>typeof x==="string"?x:(x?.nome??x?.name??x?.unidade??x?.unit??"")).map(x=>String(x).trim()).filter(Boolean);return[...new Set(a.length?a:["Un"])]}
function image(d){return d.imagemUrl||d.imagem||d.imageUrl||d.foto||d.image||d.icon||d.url||d.img||""}function find(id){return Object.values(P).flat().find(p=>p.id===id)}function K(id,u){return id+"::"+u}
async function load(){try{let s=await getDocs(collection(db,"produtos"));s.forEach(d=>{let x=d.data();if((x.ativo??x.active??true)===false)return;let p={id:d.id,name:x.nome||x.name||"Produto",image:image(x),units:getUnits(x)};P[category(x.categoria??x.category)].push(p)});renderCats();render()}catch(e){console.error(e);$("products").innerHTML="<div class=empty>Não foi possível carregar os produtos agora.</div>"}}
function renderCats(){$("cats").innerHTML=Object.keys(P).map(k=>"<button class=cat data-cat="+k+" type=button><span>"+META[k][1]+"</span><b>"+META[k][0]+"</b><small>"+P[k].length+" item(ns)</small></button>").join("");document.querySelectorAll(".cat").forEach(b=>b.onclick=()=>{catNow=b.dataset.cat;render()})}
function productCard(p){let u=U[p.id]||p.units[0],q=C[K(p.id,u)]?.quantity||0,im=p.image?"<img src=\""+esc(p.image)+"\" alt=\""+esc(p.name)+"\" loading=lazy>":"🍏";return"<article class=product><div class=photo>"+im+"</div><h3>"+esc(p.name)+"</h3><div class=units>"+p.units.map(x=>"<button class=unit data-id=\""+p.id+"\" data-unit=\""+x+"\">"+x+"</button>").join("")+"</div><div class=qty><button class=minus data-id=\""+p.id+"\" data-unit=\""+u+"\">−</button><input class=qinput data-id=\""+p.id+"\" data-unit=\""+u+"\" type=number min=0 step="+(N(u)==="kg"?.1:1)+" value="+q+"><button class=plus data-id=\""+p.id+"\" data-unit=\""+u+"\">+</button></div></article>"}
function render(){let q=N($("search").value),e=Object.entries(P);if(catNow)e=e.filter(x=>x[0]===catNow);if(q)e=e.map(x=>[x[0],x[1].filter(p=>N(p.name).includes(q))]).filter(x=>x[1].length);if(!e.length){$("products").innerHTML="<div class=empty>Nenhum produto encontrado.</div>";return}$("products").innerHTML=e.map(x=>"<section class=block><div class=blockhead><h2>"+META[x[0]][1]+" "+META[x[0]][0]+"</h2><small>"+x[1].length+" item(ns)</small></div><div class=grid>"+x[1].map(productCard).join("")+"</div></section>").join("");bind()}
function setQty(id,u,v){let p=find(id),q=num(v);if(!p)return;q=N(u)==="kg"?Math.round(q*10)/10:Math.round(q);let k=K(id,u);if(q<=0)delete C[k];else C[k]={id:id,name:p.name,unit:u,quantity:q,obs:C[k]?.obs||""};U[id]=u;update()}
function bind(){document.querySelectorAll(".unit").forEach(b=>b.onclick=()=>{U[b.dataset.id]=b.dataset.unit;render()});document.querySelectorAll(".qinput").forEach(i=>i.onchange=()=>setQty(i.dataset.id,i.dataset.unit,i.value));document.querySelectorAll(".plus").forEach(b=>b.onclick=()=>setQty(b.dataset.id,b.dataset.unit,(C[K(b.dataset.id,b.dataset.unit)]?.quantity||0)+(N(b.dataset.unit)==="kg"?.1:1)));document.querySelectorAll(".minus").forEach(b=>b.onclick=()=>setQty(b.dataset.id,b.dataset.unit,(C[K(b.dataset.id,b.dataset.unit)]?.quantity||0)-(N(b.dataset.unit)==="kg"?.1:1)))}
function update(){$("count").textContent=Object.keys(C).length;renderCart();render()}
function renderCart(){let e=Object.entries(C);if(!e.length){$("cartlist").innerHTML="<div class=empty>Sua sacola está vazia.</div>";return}$("cartlist").innerHTML=e.map(([k,i])=>"<article class=item><div class=itemrow><div class=iteminfo><div class=itemtitle><b>"+esc(i.name)+"</b><span class=itemqty data-edit=\""+k+"\">"+fmt(i.quantity)+" "+i.unit+"</span></div><div class=sub>Toque na quantidade para alterar</div><button class=obsbtn data-obs=\""+k+"\">"+(i.obs?"✎ Editar observação":"＋ Adicionar observação do item")+"</button><div class=obs id=\"obs-"+k+"\"><textarea id=\"oin-"+k+"\">"+esc(i.obs)+"</textarea><button class=saveobs data-save=\""+k+"\">Salvar observação</button></div></div><button class=remove data-remove=\""+k+"\">×</button></div></article>").join("");document.querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>{delete C[b.dataset.remove];update()});document.querySelectorAll("[data-obs]").forEach(b=>b.onclick=()=>$( "obs-"+b.dataset.obs).classList.toggle("show"));document.querySelectorAll("[data-save]").forEach(b=>b.onclick=()=>{C[b.dataset.save].obs=$( "oin-"+b.dataset.save).value.trim();renderCart()});document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>openEdit(b.dataset.edit))}
function openEdit(k){let i=C[k],p=find(i.id);editKey=k;$("mname").textContent=i.name;$("munit").innerHTML=(p?.units||[i.unit]).map(u=>"<option value=\""+u+"\">"+u+"</option>").join("");$("munit").value=i.unit;$("mqty").value=i.quantity;$("modal").classList.add("show")}
function closeEdit(){$("modal").classList.remove("show");editKey=null}function saveEdit(){if(!editKey)return;let o=C[editKey],u=$("munit").value,q=num($("mqty").value);q=N(u)==="kg"?Math.round(q*10)/10:Math.round(q);delete C[editKey];if(q>0)C[K(o.id,u)]={id:o.id,name:o.name,unit:u,quantity:q,obs:o.obs||""};U[o.id]=u;closeEdit();update()}
function showCart(){$("catalog").classList.remove("on");$("cart").classList.add("on");scrollTo(0,0);renderCart()}function showCatalog(){$("cart").classList.remove("on");$("catalog").classList.add("on");scrollTo(0,0)}function setType(t){type=t;$("delivery").classList.toggle("active",t==="Entrega");$("pickup").classList.toggle("active",t==="Retirada");$("addressbox").style.display=t==="Entrega"?"block":"none"}function toast(t){let x=$("toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),1800)}
function send(){let items=Object.values(C),d=$("date").value,a=$("address").value.trim();if(!items.length)return toast("Sua sacola está vazia");if(!d)return toast("Escolha a data");if(type==="Entrega"&&!a)return toast("Informe o endereço");let m="🛒 *NOVO PEDIDO - SAMUEL FRUTAS*\n-----------------------------------\n\n";items.forEach(i=>{m+="• *"+i.name+"*: "+fmt(i.quantity)+" "+i.unit+"\n";if(i.obs)m+="  _Obs: "+i.obs+"_\n"});m+="\n-----------------------------------\n📅 *Data:* "+d.split("-").reverse().join("/")+"\n🚚 *Tipo:* "+type+"\n";if(type==="Entrega")m+="📍 *Endereço:* "+a+"\n";let g=$("general").value.trim();if(g)m+="📝 *Observação geral:* "+g+"\n";window.open("https://wa.me/"+WA+"?text="+encodeURIComponent(m),"_blank")}
$("home").onclick=showCatalog;$("bag").onclick=showCart;$("back").onclick=showCatalog;$("search").oninput=()=>{catNow=null;render()};$("delivery").onclick=()=>setType("Entrega");$("pickup").onclick=()=>setType("Retirada");$("send").onclick=send;$("close").onclick=closeEdit;$("modal").querySelector(".shade").onclick=closeEdit;$("msave").onclick=saveEdit;$("mminus").onclick=()=>{$("mqty").value=Math.max(0,num($("mqty").value)-(N($("munit").value)==="kg"?.1:1))};$("mplus").onclick=()=>{$("mqty").value=num($("mqty").value)+(N($("munit").value)==="kg"?.1:1)};let d=new Date();d.setDate(d.getDate()+1);$("date").value=d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0");setType("Entrega");load();