import { db } from "./firebase.js";
import { collection,getDocs } from "https://www.gstatic.com/firebasejs/10.8.0/firebase-firestore.js";
const WHATSAPP_NUMBER="5521972837869";
let products=[];let cart=[];let category="frutas";let orderType="Entrega";
const $=id=>document.getElementById(id);
const normalize=s=>String(s||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"");
function categoryOf(d){const c=normalize(d.categoria||d.category);const n=normalize(d.nome||d.name);if(c.includes("legume"))return"legumes";if(c.includes("verdura"))return"verduras";if(c.includes("agua")||c.includes("ovo")||n.includes("ovo"))return"aguaOvos";return"frutas"}
function unitsOf(d){const u=d.unidadesMedida;if(u&&typeof u==="object"){const a=[];if(u.unidade)a.push("UN");if(u.quilo)a.push("KG");if(u.maco)a.push("MAÇO");if(u.duzia)a.push("DÚZIA");if(u.lote)a.push("LOTE"+(u.quantidadePorLote?" C/"+u.quantidadePorLote:""));if(u.bdj)a.push("BDJ");if(u.umQuarto)a.push("¼");if(u.umOitavo)a.push("⅛");if(u.metade)a.push("½");if(a.length)return a}return["UN"]}
function imageOf(d){return d.imagemUrl||d.imagem||d.imageUrl||d.foto||d.image||d.icon||d.url||d.img||""}
async function load(){const snap=await getDocs(collection(db,"produtos"));products=[];snap.forEach(x=>{const d=x.data();const ativo=d.ativo!==undefined?d.ativo:d.active!==undefined?d.active:true;if(ativo)products.push({id:x.id,name:d.nome||d.name||"Produto",cat:categoryOf(d),img:imageOf(d),units:unitsOf(d)})});products.sort((a,b)=>a.name.localeCompare(b.name,"pt-BR"));renderHome();renderProducts()}
function img(p){return p.img?'<img src="'+String(p.img).replaceAll('"','&quot;')+'" alt="">':'<span style="font-size:34px">🍎</span>'}
function renderHome(){const cats=[["frutas","🍌 Frutas"],["legumes","🥦 Legumes"],["verduras","🥬 Verduras"],["aguaOvos","🥥 Água / Ovos"]];$("categoryChips").innerHTML=cats.map(c=>'<button class="chip '+(category===c[0]?"selected":"")+'" onclick="setCategory(\''+c[0]+'\')">'+c[1]+"</button>").join("");const f=products.filter(p=>p.cat===category).slice(0,6);$("featured").innerHTML=f.map(p=>'<button class="feature-card" onclick="add(\''+p.id+'\')" style="text-align:left"><div class="feature-img">'+img(p)+'</div><strong>'+esc(p.name)+'</strong><small>'+esc(p.units[0]||"UN")+"</small></button>").join("")||'<div class="card">Nenhum produto encontrado.</div>'}
function renderProducts(list){if(!list)list=products.filter(p=>p.cat===category);$("productsTitle").textContent=category==="aguaOvos"?"Água / Ovos":category.charAt(0).toUpperCase()+category.slice(1);$("productList").innerHTML=list.map(p=>'<div class="product-card"><div class="product-img">'+img(p)+'</div><div class="product-info"><strong>'+esc(p.name)+'</strong><small>'+p.units.join(" · ")+'</small><div class="product-actions"><select class="unit" id="u-'+p.id+'">'+p.units.map(u=>"<option>"+esc(u)+"</option>").join("")+'</select><button class="add" onclick="add(\''+p.id+"\')">🛒 Adicionar</button></div></div></div>").join("")||'<div class="card">Nenhum produto encontrado.</div>'}
function add(id){const p=products.find(x=>x.id===id);if(!p)return;const unit=$("u-"+id)?.value||p.units[0];const x=cart.find(i=>i.id===id&&i.unit===unit);if(x)x.qty++;else cart.push({id:p.id,name:p.name,img:p.img,unit:unit,qty:1,note:""});updateCart();openCart()}
function updateCart(){const count=cart.reduce((s,x)=>s+x.qty,0);$("cartCount").textContent=count;$("navBadge").textContent=count;$("cartSummary").textContent=count+" "+(count===1?"item":"itens")}
function renderCart(){if(!cart.length){$("cartList").innerHTML='<div class="card" style="text-align:center;padding:35px">Sua sacola está vazia.</div>';return}$("cartList").innerHTML=cart.map((x,i)=>'<div class="item"><div class="item-head"><img class="item-img" src="'+(x.img||"")+'" onerror="this.style.display=\'none\'" alt=""><div class="item-main"><strong>'+esc(x.name)+'</strong><div class="item-controls"><select onchange="changeUnit('+i+',this.value)">'+unitsOf(products.find(p=>p.id===x.id)||{}).map(u=>'<option '+(u===x.unit?"selected":"")+">"+esc(u)+"</option>").join("")+'</select><button onclick="changeQty('+i+',-1)">−</button><b>'+x.qty+'</b><button onclick="changeQty('+i+',1)">+</button><button class="remove" onclick="removeItem('+i+')">🗑</button></div></div></div><div class="item-note"><label>OBSERVAÇÃO DO ITEM (opcional)</label><textarea maxlength="200" placeholder="Ex.: Quero bem maduro, por favor." onchange="setNote('+i+',this.value)">'+esc(x.note)+'</textarea></div></div>').join("")}
function changeQty(i,d){cart[i].qty+=d;if(cart[i].qty<=0)cart.splice(i,1);updateCart();renderCart()}
function changeUnit(i,u){const same=cart.findIndex((x,j)=>j!==i&&x.id===cart[i].id&&x.unit===u);if(same>=0){cart[same].qty+=cart[i].qty;cart.splice(i,1)}else cart[i].unit=u;renderCart();updateCart()}
function setNote(i,v){cart[i].note=v}
function removeItem(i){cart.splice(i,1);renderCart();updateCart()}
function searchProducts(q){const n=normalize(q);renderProducts(products.filter(p=>p.cat===category&&(!n||normalize(p.name).includes(n))))}
function setCategory(c){category=c;renderHome();showProducts()}
function setOrderType(t){orderType=t;$("deliveryChoice").classList.toggle("selected",t==="Entrega");$("pickupChoice").classList.toggle("selected",t==="Retirada");$("addressCard").style.display=t==="Entrega"?"block":"none"}
function openCheckout(){if(!cart.length)return alert("Sua sacola está vazia.");setOrderType(orderType);if(!$("deliveryDate").value)setTomorrow();show("checkoutView")}
function setTomorrow(){const d=new Date();d.setDate(d.getDate()+1);$("deliveryDate").value=d.toISOString().slice(0,10)}
function finishOrder(){if(!cart.length)return;const date=$("deliveryDate").value;if(!date)return alert("Escolha a data do pedido.");const address=$("address").value.trim();if(orderType==="Entrega"&&!address)return alert("Informe o endereço da entrega.");let msg="🛒 *NOVO PEDIDO - SAMUEL FRUTAS*\n\n";cart.forEach(x=>{msg+="• *"+x.qty+" "+x.unit+" de "+x.name+"*";if(x.note.trim())msg+="\n  _Obs: "+x.note.trim()+"_";msg+="\n"});msg+="\n📅 *Data:* "+formatDate(date)+"\n🚚 *Tipo:* "+orderType+"\n";if(orderType==="Entrega")msg+="📍 *Endereço:* "+address+"\n";const obs=$("generalObs").value.trim();if(obs)msg+="📝 *Observação geral:* "+obs+"\n";window.location.href="https://wa.me/"+WHATSAPP_NUMBER+"?text="+encodeURIComponent(msg)}
function formatDate(v){const a=v.split("-");return a[2]+"/"+a[1]+"/"+a[0]}
function show(id){document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));$(id).classList.add("active");window.scrollTo({top:0,behavior:"smooth"})}
function goHome(){show("homeView");renderHome()}
function showProducts(){show("productsView");renderProducts()}
function openCart(){show("cartView");renderCart()}
function esc(s){return String(s||"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
window.goHome=goHome;window.showProducts=showProducts;window.openCart=openCart;window.openCheckout=openCheckout;window.setCategory=setCategory;window.add=add;window.changeQty=changeQty;window.changeUnit=changeUnit;window.setNote=setNote;window.removeItem=removeItem;window.searchProducts=searchProducts;window.setOrderType=setOrderType;window.finishOrder=finishOrder;
load().catch(e=>{console.error(e);$("featured").innerHTML='<div class="card">Não foi possível carregar os produtos. Verifique a conexão.</div>'})